// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package api

import (
	"go-gin-project/api/controller"
	"go-gin-project/api/repository"
	"go-gin-project/api/service"
	"go-gin-project/config"
)

// Injectors from injection.go:

func InitializeTerminalController() *controller.TerminalController {
	db := config.DatabaseConnection()
	terminalRepository := repository.NewTerminalRepositoryImpl(db)
	validate := config.NewValidator()
	terminalService := service.NewTerminalServiceImpl(terminalRepository, validate)
	terminalController := controller.NewTerminalController(terminalService)
	return terminalController
}
